# Generated by Django 5.1.1 on 2024-09-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255, verbose_name='title')),
                ('title2', models.CharField(max_length=255, verbose_name='title')),
                ('subtitle', models.CharField(max_length=255, verbose_name='subtitle')),
                ('text', models.TextField(verbose_name='text')),
                ('image', models.ImageField(upload_to='siteimages', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Carousel',
                'verbose_name_plural': 'Carousels',
                'ordering': ['title1', 'title2'],
            },
        ),
    ]
