# Generated by Django 5.1.1 on 2024-09-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_brands_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.ManyToManyField(blank=True, null=True, to='Core.brands'),
        ),
    ]
