# Generated by Django 5.1.1 on 2024-09-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_product_brands_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='Core.brands'),
        ),
    ]
