# Generated by Django 5.1.1 on 2024-09-28 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_product_brand_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='category name')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, verbose_name='brand')),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subcate_r', to='Core.categor')),
            ],
        ),
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('price', models.IntegerField(verbose_name='price')),
                ('img', models.ImageField(upload_to='products', verbose_name='image')),
                ('subc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subc_r', to='Core.subcategory')),
            ],
        ),
    ]
