# Generated by Django 5.1.1 on 2024-09-28 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_categor_subcategory_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='cate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cate_r', to='Core.categor'),
            preserve_default=False,
        ),
    ]
