# Generated by Django 5.1.1 on 2024-09-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_remove_brands_products_alter_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='cate',
        ),
        migrations.RemoveField(
            model_name='prod',
            name='cate',
        ),
        migrations.RemoveField(
            model_name='prod',
            name='subc',
        ),
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterField(
            model_name='category',
            name='subcategory',
            field=models.ManyToManyField(blank=True, related_name='sub', to='Core.brands'),
        ),
        migrations.DeleteModel(
            name='Categor',
        ),
        migrations.DeleteModel(
            name='Prod',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
