# Generated by Django 5.1.1 on 2024-09-28 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_product_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
