# Generated by Django 5.1.1 on 2024-09-28 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0015_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default='Nobrand', on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='Core.brands'),
        ),
    ]
