# Generated by Django 5.1.1 on 2024-09-28 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0018_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='Core.category'),
            preserve_default=False,
        ),
    ]
