# Generated by Django 5.1.1 on 2024-09-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0020_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
